Current run is terminating due to exception: mat1 dim 1 must match mat2 dim 0
Engine run is terminating due to exception: mat1 dim 1 must match mat2 dim 0
Traceback (most recent call last):
  File "main.py", line 357, in <module>
    run(args)
  File "main.py", line 208, in run
    trainer.run(train_loader, max_epochs=args.epochs)
  File "/home/igor/anaconda3/envs/sm/lib/python3.8/site-packages/ignite/engine/engine.py", line 702, in run
    return self._internal_run()
  File "/home/igor/anaconda3/envs/sm/lib/python3.8/site-packages/ignite/engine/engine.py", line 775, in _internal_run
    self._handle_exception(e)
  File "/home/igor/anaconda3/envs/sm/lib/python3.8/site-packages/ignite/engine/engine.py", line 469, in _handle_exception
    raise e
  File "/home/igor/anaconda3/envs/sm/lib/python3.8/site-packages/ignite/engine/engine.py", line 745, in _internal_run
    time_taken = self._run_once_on_dataset()
  File "/home/igor/anaconda3/envs/sm/lib/python3.8/site-packages/ignite/engine/engine.py", line 850, in _run_once_on_dataset
    self._handle_exception(e)
  File "/home/igor/anaconda3/envs/sm/lib/python3.8/site-packages/ignite/engine/engine.py", line 469, in _handle_exception
    raise e
  File "/home/igor/anaconda3/envs/sm/lib/python3.8/site-packages/ignite/engine/engine.py", line 833, in _run_once_on_dataset
    self.state.output = self._process_function(self, self.state.batch)
  File "/home/igor/Documents/VG_Architectural_Adversarial_Robustness/LinearityIQA/modified_ignite_engine.py", line 48, in _update
    y_pred = model(x)
  File "/home/igor/anaconda3/envs/sm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/igor/Documents/VG_Architectural_Adversarial_Robustness/LinearityIQA/IQAmodel.py", line 123, in forward
    f, pq = self.extract_features(x)
  File "/home/igor/Documents/VG_Architectural_Adversarial_Robustness/LinearityIQA/IQAmodel.py", line 109, in extract_features
    x6 = self.dr6(x6)
  File "/home/igor/anaconda3/envs/sm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/igor/anaconda3/envs/sm/lib/python3.8/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/home/igor/anaconda3/envs/sm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/igor/anaconda3/envs/sm/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 94, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/igor/anaconda3/envs/sm/lib/python3.8/site-packages/torch/nn/functional.py", line 1753, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: mat1 dim 1 must match mat2 dim 0
